version: 2 

sources: 
  - name: le_wagon_7_dec
    description: ceci est un test pour récupérer le projet dans DBT
    tables:
    - name: raw_gz_product
    - name: raw_gz_ship
    - name: raw_sales

